pingcap/monitoring

reload/main.go

Function
Add error when watching directory failed

Add-error-when-watch-dir-failed

---

monitor/v2.1.16/Dockerfile
monitor/v2.1.16/dashboards/binlog.json
monitor/v2.1.16/dashboards/pd.json
monitor/v2.1.16/dashboards/tidb.json
monitor/v2.1.16/dashboards/tikv_pull.json
monitor/v2.1.16/init.sh
monitor/v2.1.16/rules/pd.rules.yml
monitor/v2.1.16/rules/tidb.rules.yml
monitor/v2.1.16/rules/tikv-pull.rules.yml
monitor/v3.0.2/Dockerfile
monitor/v3.0.2/dashboards/binlog.json
monitor/v3.0.2/dashboards/overview.json
monitor/v3.0.2/dashboards/pd.json
monitor/v3.0.2/dashboards/tidb.json
monitor/v3.0.2/dashboards/tikv_details.json
monitor/v3.0.2/dashboards/tikv_summary.json
monitor/v3.0.2/dashboards/tikv_trouble_shooting.json
monitor/v3.0.2/init.sh
monitor/v3.0.2/rules/pd.rules.yml
monitor/v3.0.2/rules/tidb.rules.yml
monitor/v3.0.2/rules/tikv.rules.yml

**Function**
Add 2.1.16 and 3.0.2 TiDB monitor

Monitor:Add new monitor version

---

cmd/main.go
monitor/v2.1.12/dashboards/overview_pull.json
monitor/v2.1.13/dashboards/overview_pull.json
monitor/v2.1.14/dashboards/overview_pull.json
monitor/v2.1.15/dashboards/overview_pull.json
monitor/v2.1.16/dashboards/overview_pull.json

**Function**
Supporting overview_pull format dashboard
**Test**
There are overview_pull.json in auto generate directory.

Monitoring: support overview_pull format dashboard

---

k8s-cluster-monitor/manifests/prometheus/kube-state-metrics-serviceMonitor.yaml
k8s-cluster-monitor/manifests/prometheus/prometheus-serviceMonitorElasticSearchExporter.yaml

Signed-off-by: qiffang <947321353@qq.com>
**Function**
Fix duplicate target false alerts

Monitoring: update duplicate target false alerts.

---

platform-monitoring/ansible/grafana/blackbox_exporter.json
platform-monitoring/ansible/grafana/disk_performance.json
platform-monitoring/ansible/grafana/kafka.json
platform-monitoring/ansible/grafana/node.json
platform-monitoring/ansible/rule/blacker.rules.yml
platform-monitoring/ansible/rule/bypass.rules.yml
platform-monitoring/ansible/rule/kafka.rules.yml
platform-monitoring/ansible/rule/node.rules.yml

Ansible - Add machine monitor dashboard and alert rules

---

cmd/monitoring.go

Add token in command line
Test
{code}
Usage:
load [flags]
Flags:
--auto-push           auto generate new branch from master and push auto-generate files to the branch
--config string       the monitoring configuration file.
-h, --help                help for load
--output-dir string   the base directory of the program (default ".")
--tag string          the tag of pull monitoring repo.
--token string        the token of github (default ".")
{code}

Tools :Add token in command line

---

platform-monitoring/ansible/grafana/blackbox_exporter.json

Problem Summary: add tiflash to grafana dashboard
Tests 
- No code

add tiflash to grafana

---

cmd/init.sh

Fix https://github.com/pingcap/tidb-operator/issues/3144

fix cpu and memory metrics for tiflash proxy

---

cmd/init.sh

Revert "change job label to component to support monitoring multi clusters"

---

cmd/init.sh
monitoring.yaml
pkg/operator/dashboards.go
platform-monitoring/operator/init.sh

Add ticdc monitoring configuration to support ticdc monitor in TiDB Operator.
TiDB Operator has already supported ticdc monitor.
Fix [#3710](https://github.com/pingcap/tidb-operator/issues/3710)
Add ticdc monitoring configuration.
1. Test env perpare
```
kind create cluster
./hack/local-up-operator.sh
kc apply -f examples/basic/tidb-cluster.yaml
```
2. Build test image
```shell
cd cmd/
go build monitoring.go
./monitoring.go --config ../monitoring.yaml --tag v4.0.9
docker build . xxx
docker push xxx
```
3. Deploy tidb monitor
tidb-monitor.yaml
```
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
name: basic
spec:
clusters:
- name: basic
prometheus:
baseImage: prom/prometheus
version: v2.18.1
grafana:
baseImage: grafana/grafana
version: 6.1.6
initializer:
baseImage: …
```

support ticdc monitor

---

platform-monitoring/ansible/grafana/disk_performance.json

delete node_disk_written_bytes_totalwritten 
add node_disk_written_bytes_total
Link https://github.com/pingcap/tiup/issues/1225

fix Disk Bandwidth Write metrics

---

platform-monitoring/operator/init.sh

Reslove https://github.com/pingcap/tidb-operator/issues/3292.

Operator init.sh no need to replace the cluster name.

---

platform-monitoring/operator/grafana/pods.json

adapt k8s 1.16+ [#80376](https://github.com/kubernetes/kubernetes/pull/80376)
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#removed-metrics

adapt k8s 1.16+

---

platform-monitoring/operator/init.sh

Close https://github.com/pingcap/tidb-operator/issues/4022
Fix cluster option not display question.

show cluster option in dashboards

---

monitoring.yaml

This is part job of step-4 in pingcap/ticdc#3749

rename ticdc to tiflow

---

cmd/Dockerfile
platform-monitoring/operator/Dockerfile
reload/Dockerfile
reload/Dockerfile_buildx

[cp] add Dockerfile_buildx for reload

---

reload/Dockerfile_buildx

* add dockerfile for multi-arch to release-5.2

release 5.2 add buildx dockerfile

---

cmd/init.sh
monitoring.yaml
pkg/operator/dashboards.go
platform-monitoring/operator/init.sh

Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

add tikv-cdc metric

---

cmd/monitoring.go
monitoring.yaml

Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

fix main tag

---

cmd/init.sh
pkg/operator/dashboards.go
platform-monitoring/operator/init.sh

add ticdc summary dashboard

---

Makefile
scripts/build_tiup_grafana.sh
scripts/prepare_dashboards.sh

use makefile instead of script to clearly show what is generated

feat: add makefile target

---

.gitmodules

We will make the submodule auto update.
It's are for CD refactoring to build prometheus tiup package.

ci: add ng-monitoring as a submodule

---

Makefile
scripts/prepare_prometheus.sh

ci: add make task `output/prometheus` to compose the most files for prometheus tiup package

---

Makefile
scripts/prepare_prometheus.sh

Reverts pingcap/monitoring#296

Revert "ci: add make task `output/prometheus` to compose the most files for prometheus tiup package (#283) (#293)"

---

scripts/prepare_prometheus.sh

ci: fix prepare_prometheus.sh

---

dependencies.yaml
scripts/build_tiup_grafana.sh
scripts/prepare_prometheus.sh

ci: control the third-party versions with dependencies

---

scripts/prepare_prometheus.sh

ci(scripts): fix prepare_prometheus.sh script

---

scripts/build_tiup_grafana.sh

ci: fix grafana script

---

.github/renovate.json
dependencies.yaml

ci: fix renovate config

---

.github/renovate.json
dependencies.yaml
scripts/build_tiup_grafana.sh
scripts/prepare_prometheus.sh

chore: make building reproducibe

---

go.mod

set the go version without patch part.

build: update go.mod
